name: Delta RSS

on:
  workflow_dispatch:
#  schedule:
#      - cron: '15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run monitor
        run: python main.py
      - name: List feeds
        run: find feeds
