name: Delta RSS

on:
  workflow_dispatch:
#  schedule:
#      - cron: '15 * * * *'

jobs:
  build_rss_feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run monitor
        run: python main.py
      - name: Commit feeds
        run: |
          git config --global user.email "no-reply@deepseas.com"
          git config --global user.name "DeepSeas Bot"
          git add feeds/*
          git commit -m "Update feeds `date`"
          git push
